### ISSUE TITLE
Can you give example for decrypte Mimic 

### ISSUE THREAD

**Issue by Markus250** [facct-ransomware/Ransomware#1]
Hello! Can please give me example how to decrypt example file for Mimic (test1.jpg.xxxxxxxxxx)
path: Mimic/tools/
Thanks!

**Comment by f6-dfir** [comment]
Sorry! I got the scripts mixed up. I've already fixed it. :)
Please try again

**Comment by Markus250** [comment]
Thank you! It worked! Please tell me how you generated privkey.bin. We were hacked and planted with a mimic, do we have a chance to use your utility?
In you file Mimic/attackers.txt there are emails that were written to us in an extortion lette:
v7.5
.datastore@cyberfear.com
datastore@cyberfear.com
back2up@swismail.com

**Comment by rivitna** [comment]
I generated these keys myself for demo.
To decrypt your files using my script, you will need the private key that the attackers have

**Comment by Markus250** [comment]
Thank you very much for the work done!
